apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.fullnameOverride }}-db
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.dbSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.fullnameOverride }}-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataSize }}
